/*
 * Problem002
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

#include <iostream>

int main() {

    int sum  = 1;        // sum of the sequence
    int prev = 1;        // value added to each sum
    int temp = 0;        // temporary value

    int evenSum = 0;    //sum of even values

    while (sum < 4000000)
    {
        temp = sum;
        sum += prev;
        prev = temp;

        if (sum % 2 == 0)
        {
            evenSum += sum;
        }

        std:: cout << evenSum << " ";
    }

    std::cout << std::endl << "The sum of even values is: " << evenSum << std::endl;

    return 0;
}

/*
 * The answer is 4613732.
 */